### ISSUE TITLE
Embed live code snippets in GL JS examples

### ISSUE THREAD

**Issue by adrianababakanian** [mapbox/mapbox-gl-js-docs#139]
## Motivation
Currently, the flow for working off of sample code in the [Mapbox GL JS examples page](https://docs.mapbox.com/mapbox-gl-js/examples/) looks something like the following:

1. Creating an empty HTML file.
2. Copy-pasting the example into the new file. 
3. Making adjustments to customize the example from there.

## Proposal
Creating a simple embedded IDE (similar to [JSFiddle](https://jsfiddle.net/), [JS Bin](https://jsbin.com/), or even the code cells in [ObservableHQ](https://observablehq.com/demo)) to display & run sample code would reduce friction for developers experimenting with existing GL JS examples. The overhead of copy-pasting entire HTML files to tweak a single line of JavaScript is quite high -- and is not representative of how easy it is to customize and build complex Mapbox-based applications off of existing examples.  

An HTML-only IDE would be a great first step (By "HTML-only", I mean an IDE that only supports editing a single HTML file. CSS and JS would remain inline in the form of `<style>` and `<script>` tags). In the long run, it would be useful to modularize the examples (i.e. use external `.js` script files for JavaScript instead of `<script>` tags), since the boilerplate HTML used by each is virtually identical. 

Additionally, importing GeoJSON data as a variable rather than defining the variable within the HTML's `<script>` tags would help de-clutter examples. For example, consider the `places` variable in the [Filter symbols by toggling a list](https://docs.mapbox.com/mapbox-gl-js/example/filter-markers/) code snippet. This `FeatureCollection` could live in a separate `.json` file to make the code more readable. To maintain the benefit of brevity that comes from keeping all the code in a single file, perhaps an option to toggle between the `modular` and `single file` options could be added.

cc @mapbox/docs

**Comment by katydecorah** [comment]
@adrianababakanian I think this is excellent! I started looking into options to make example page code interactive:


- CodePen has [prefill embeds](https://blog.codepen.io/documentation/prefill-embeds/), which will take code blocks on a given page and turn it into an interactive environment.
- [JSFiddle has embeds](https://docs.jsfiddle.net/embedding-fiddles), but it appears we would have to already create the fiddle in order to embed it.
- [CodeMirror](https://codemirror.net/) appears to be the standard in powering JavaScript web text editors (like CodePen, JSFiddle). If we needed to build it custom, I imagine we’d start there.

(I'm also happy to hear other suggestions, there are the ones that I had top of mind.)

## Considerations

Using something out of the box (like CodePen's prefill embeds) will prevent us from having to own the IDE codebase, but presents an issue: 
- how can the IDE use the Mapbox token (not the user token) to load the map? Right now the iFrame that shows the example map uses the Mapbox token and the code shows the user token. We do this to prevent a logged in user from accruing usage as they load examples while making the user token readily available. This is the main problem I found with using CodePen’s prefill embeds and haven’t solved yet and may point to us building something custom to accommodate this case.

## Stopgap

While we experiment different IDE tools or building our own, we could roll out “Edit in CodePen/JSFiddle” options now. ([Mapbox.js has this](https://docs.mapbox.com/mapbox.js/example/v1.0.0/).) These edit buttons should be fairly straightforward (especially since we have prior art from Mapbox.js) and ease some friction for the user until we can implement something interactive for the user.

> ![Mapbox.js example page with Edit in JSFiddle button](https://user-images.githubusercontent.com/2180540/69160146-0eb11280-0ab7-11ea-9375-e04da22f0399.png)
>_Mapbox.js example page with "Edit in JSFiddle" button_

## Next actions:

* [ ] Add “Edit in CodePen/JSFiddle” buttons to each example @katydecorah 
* [ ] Continue researching interactive code editors or decide to build our own IDE

**Comment by adrianababakanian** [comment]
Thank you for following up with all these ideas @katydecorah ! The access token issue you mentioned is definitely one of the main blockers to using an existing out-of-the-box solution. 

Adding the "Edit in CodePen/JSFiddle" buttons for each example would be a really great first step. Let me know if there's anything I can do to help with next actions 🎉

**Comment by katydecorah** [comment]
@adrianababakanian Are you interested/have time to review #147 which adds the edit buttons to examples?

**Comment by adrianababakanian** [comment]
@katydecorah Definitely, will do!

**Comment by katydecorah** [comment]
I wanted to share that the Edit buttons have been performing very well.

These buttons are clicked on average 272 times a day (JSFiddle 57.6%; CodePen 42.4%)
![image](https://user-images.githubusercontent.com/2180540/70163210-15ca4a00-168d-11ea-82a6-38453846fec0.png)

**Comment by andrewharvey** [comment]
:heart: the new edit buttons. My personal preference would be to either have the middle mouse to open in a new tab work like regular links, or just have them open in a new tab by default. Once you've opened an example to edit, you'd likely still want to browser other examples or the API docs so new tab would be nicer I think.

**Comment by adrianababakanian** [comment]
Agreed @andrewharvey ! I opened a small PR to change the default behavior to opening in a new tab. Glad to hear you are enjoying the buttons.

**Comment by asheemmamoowala** [comment]
Closed by #147 and #167
