### ISSUE TITLE
text-radial-offset and text-variable-anchor are not layout properties error on variable label placement example

### ISSUE THREAD

**Issue by colleenmcginnis** [mapbox/mapbox-gl-js-docs#160]
A user submitted through the feedback widget that the [Variable label placement example](https://docs.mapbox.com/mapbox-gl-js/example/variable-label-placement/) was giving them console errors that `text-radial-offset` and `text-variable-anchor` are not layout properties. 

My assumption is that they are using an older version of Mapbox GL JS that doesn't support these properties. Does that sound right @mapbox/gl-js? Would we ever want to consider noting which versions of an example are compatible with? I know we already note that these properties are only compatible with >= 0.54.0 in the [Style Specification](https://docs.mapbox.com/mapbox-gl-js/style-spec/#layout-symbol-text-variable-anchor), but wondering if you've ever thought about doing something / think it would be beneficial to do something similar for examples? Or should users assume every example is only compatible with the most recent version?

cc @mapbox/docs

**Comment by asheemmamoowala** [comment]
> Would we ever want to consider noting which versions of an example are compatible with?
> Or should users assume every example is only compatible with the most recent version?

There have been times when examples have been updated to take advantage of the newest features. And we should be doing more of this to help developers solve their problems in the best way provided by the SDK. 
We could add the version of GL-JS at which an example is added/modified to the docs or just indicate that a feature is 🆕 🎉. Ideally we are moving developers to the latest release, instead of trying to help them work with older releases.

**Comment by colleenmcginnis** [comment]
This is not something we're going to pursue. Since we don't maintain versioned API reference docs either, I think it's reasonable for us to expect users to know examples apply to the most recent version (and that version is even in URLs in the code snippet).
