### ISSUE TITLE
Support pinning to latest style-spec tags as well as latest gl-js tags

### ISSUE THREAD

**Issue by danswick** [mapbox/mapbox-gl-js-docs#298]
Sometimes, style-spec updates happen outside of the normal `mapbox-gl-js` release schedule. We should be able to update the style spec without getting `mapbox-gl-js` out of sync.

cc @asheemmamoowala

**Comment by arindam1993** [comment]
We generally make `release-xxxx` branches, can we pin the gl-js submodule to a commit on that branch?

Or docs could consume `style-spec` as a node package, studio has some webpack config that lets it reference files within the source tree directly instead of the bundle.

**Comment by katydecorah** [comment]
> Or docs could consume style-spec as a node package, studio has some webpack config that lets it reference files within the source tree directly instead of the bundle.

I think this would work!

I did a quick test and I think we could point all the paths to the package rather than the submodule and the style-spec documentation can still build as expected.

It would also clear up the issue we encountered with #257 where we needed to add an additional step to install the style-spec submodule dependencies (and now we could remove that step).
