### ISSUE TITLE
Local geocoder docs using an old version

### ISSUE THREAD

**Issue by ogdenstudios** [mapbox/mapbox-gl-js-docs#412]
Hey everyone, 

The local address search refers to v4.2.0 for mapbox-gl-geocoder, but the current version is 4.7.0 (although I hear that isn't on the CDN right now and they're working on it). [This example](https://docs.mapbox.com/help/tutorials/local-search-geocoding-api/#add-the-geocoder) caused some problems for me since it's out of date. Just wanted to bring it to your attention. Thanks!

**Comment by katydecorah** [comment]
@ogdenstudios thanks for the heads up! 

The team is working on updating Mapbox GL JS examples with the latest version of mapbox-gl-geocoder in https://github.com/mapbox/mapbox-gl-js-docs/pull/391

Since it lives in a private repo, I'll create an internal issue to flag that the [Local search with the Geocoding API](https://docs.mapbox.com/help/tutorials/local-search-geocoding-api/#add-the-geocoder) tutorial needs to be updated as well.

**Comment by ogdenstudios** [comment]
Appreciate it, thank you!
