### ISSUE TITLE
Clarify `passive` in geolocatecontrol

### ISSUE THREAD

**Issue by HeyStenson** [mapbox/mapbox-gl-js-docs#82]
_This feedback was submitted by a user through the feedback widget on the bottom of the page._

Page: https://docs.mapbox.com/mapbox-gl-js/api/#geolocatecontrol

> The docs mention "passive - the user's location dot automatically updates, but the map's camera does not." but there does not appear to be any way to achieve this. There's also no string "passive" in the source.

![Screen Shot 2019-09-17 at 10 28 10 AM](https://user-images.githubusercontent.com/8186438/65064739-e3cf0480-d935-11e9-889d-6ee7d343e01c.png)

It's not clear to me either from this section how to change to these three states, including `passive`. This is probably worth clarifying in the docs.

**Comment by andrewharvey** [comment]
This state is not part of the public API so you can't get or set it with the public API. It is still mentioned in the docs to document the user experiences. Maybe just saying that it will start in the active state, but if the user actively moves the map then it will change to passive.

**Comment by stevage** [comment]
Came here to report something similar.

To be honest, after looking at the PR, I think it would all be clearer just removing all the text from "In this mode..." onwards. I don't think that introducing the concept of three states is actually clarifying anything much.

**Comment by andrewharvey** [comment]
I'm for leaving the documentation for the user interface states in place (together with my proposed PR), since it provides the contract with developers on how the geolocate control behaves and works. Without the documentation it's unclear how it works.

In the future we could build this into the API with a `geolocate.getState()` method at which point the documentation will be necessary anyway.
